### ISSUE TITLE
Issue with tmp folder maybe? 

### ISSUE THREAD

**Issue by nimeso** [unclecheese/silverstripe-dropzone#1]
Hi ya!

Thanks for all your hard work man!
I'm having issues... I also can't see the file in my wamp/tmp folder? hmmmm... what am I doing wrong? I get the following error displaying

====================================================================================================
MapPage.php:90 - MapPage_Controller::doCreatePOIImageForm()

SS_HTTPRequest Object
(
    [url:protected] =&gt; new-map-page/doCreatePOIImageForm/field/Image/upload
    [dirParts:protected] =&gt; Array
        (
            [0] =&gt; field
            [1] =&gt; Image
            [2] =&gt; upload
        )

    [extension:protected] =&gt; 
    [httpMethod:protected] =&gt; POST
    [getVars:protected] =&gt; Array
        (
            [url] =&gt; /new-map-page/doCreatePOIImageForm/field/Image/upload
        )

    [postVars:protected] =&gt; Array
        (
            [SecurityID] =&gt; 09cc762167db58637a614769c6279a352f4e1545
            [file] =&gt; Array
                (
                    [name] =&gt; Koala.jpg
                    [type] =&gt; image/jpeg
                    [tmp_name] =&gt; D:\wamp\tmp\php5E97.tmp
                    [error] =&gt; 0
                    [size] =&gt; 780831
                )

        )

    [headers:protected] =&gt; Array
        (
            [Mod-Rewrite] =&gt; On
            [Host] =&gt; skyline.nimeso
            [Connection] =&gt; keep-alive
            [Origin] =&gt; http://skyline.nimeso
            [User-Agent] =&gt; Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
            [Accept] =&gt; application/json
            [Cache-Control] =&gt; no-cache
            [X-Requested-With] =&gt; XMLHttpRequest
            [Referer] =&gt; http://skyline.nimeso/new-map-page
            [Accept-Encoding] =&gt; gzip, deflate
            [Accept-Language] =&gt; en-US,en;q=0.8,it;q=0.6
            [Cookie] =&gt; PHPSESSID=6stc352ul7jjd2n3dfq41876k1; bypassStaticCache=1; cms-panel-collapsed-cms-content-tools-CMSPagesController=true; cms-panel-collapsed-cms-content-tools-CMSMain=false; cms-panel-collapsed-cms-menu=false; PastMember=1
            [Content-Type] =&gt; multipart/form-data; boundary=----WebKitFormBoundaryrSiXuxDvmarBFHr2
            [Content-Length] =&gt; 781151
        )

    [body:protected] =&gt; 
    [allParams:protected] =&gt; Array
        (
            [URLSegment] =&gt; new-map-page
            [Action] =&gt; doCreatePOIImageForm
            [ID] =&gt; field
            [OtherID] =&gt; Image
        )

    [latestParams:protected] =&gt; Array
        (
            [Action] =&gt; doCreatePOIImageForm
            [ID] =&gt; field
            [OtherID] =&gt; Image
        )

    [routeParams:protected] =&gt; Array
        (
            [Controller] =&gt; ModelAsController
        )

    [unshiftedButParsedParts:protected] =&gt; 2
)

====================================================================================================

**Comment by unclecheese** [comment]
Hey, there. Thanks for being the first person to test out this module. I'm excited about it, and I'm anxious to get more people using it.

Looks like you're posting a var_dump of the request, but is there a specific error you're getting? Can I see your code?

**Comment by nimeso** [comment]
It looks great so far if I can get it working :) Thanks heaps!

```php
public function CreatePOIImageForm(){

	    $fields = new FieldList(
	    	new TextField('Name', 'Name'),
	    	new TextField('Email', 'Email'),
	    	$file = FileAttachmentField::create('Image', 'Upload a file'),
	    	new TextField("CategoryID")
		);
		
		$file->setView('grid');
	 	
	    // Create action
	    $actions = new FieldList(
			new FormAction('doCreatePOIImageForm', 'Submit')
	    );
		// Create action
		$validator = new RequiredFields('Name','Email','Image');
			
		$Form = new Form($this, 'doCreatePOIImageForm', $fields, $actions, $validator);	
		
	 	return $Form;
	}
	
	public function doCreatePOIImageForm($data){
		
		//Debug::dump($data);
		$POIImage = new MapPOIImage();
		$POIImage->Author = $data["Name"];
		$POIImage->Email = $data["Email"];
		$POIImage->write();
		
	}
```

**Comment by unclecheese** [comment]
You’re not instantiating the form properly. Check the second argument of your constructor.

aaron_carlino: {
web_developer: “leftandmain.com"
}

**Comment by nimeso** [comment]
Jezz! I feel lame :( I missed that. All working great now! woo hoo!
Thanks!

**Comment by unclecheese** [comment]
Cool! One last thing -- you might want to use `$form->saveInto($POIImage)` instead of going through the `$data` array key by key. If your `POIImage` object has a `has_one` for `Image`, the upload field will automatically save into it that way.

**Comment by nimeso** [comment]
:)
