### ISSUE TITLE
The inputs in `.attached-file-inputs` aren't being dynamically created when adding a new image on the front end

### ISSUE THREAD

**Issue by mrsteveheyes** [unclecheese/silverstripe-dropzone#10]
Hi @unclecheese ,

Thanks for this module. It's great.

I've encountered an error while using it on a fronted form. I've dragged an image onto the dropzone and it looks ok, but when I look at the code there is no input in  `div.attached-file-inputs`. So when I save the form, the file ID isn't saved into my model. Any ideas why this might be?

I don't have any javascript errors. I am including "/dropzone/javascript/file_attachment_field.js" and "/dropzone/javascript/dropzone.js" and they are loading fine. The CSS is loading in fine too.

I'm adding the field in the form as follows:

```
$fields = FieldList::create();
$fields->push(
    FileAttachmentField::create('Logo', _t('Agency.has_one_Logo'))
);
return $fields;
```

Do you need any more information from me?

**Comment by unclecheese** [comment]
Looks like you're doing everything correctly. You should not have to explicitly include those two JS files. Those should be included automatically, unless you're overriding the Requirements. If those are included twice, you could be choking the Javascript.

Here's the test I'm running:

```php
		$f = Form::create (
			$this,
			"TestForm",
			FieldList::create(
				TextField::create('Name'),
				FileAttachmentField::create('Photo')->setView('grid')
			),
			FieldList::create(
				FormAction::create('doTest','Test')
			)
		);
```

I'm not able to replicate that. Could you maybe send me a more complete code example that you're using?

**Comment by mrsteveheyes** [comment]
OK I got it working. I'm not 100% sure how.

My context is that I was using it to edit a model called Agency. On my AgencyPage (which is in the site tree) I had the following $url__handlers:
```
    private static $url_handlers = [
        'EditForm'          => 'EditForm',
        '$URLSegment/edit'  => 'edit',
        '$URLSegment'       => 'agency'
    ];
```

My edit function was: 
```
public function edit()
    {
        if($this->canEditAgency())
        {
            return $this->render();
        }
        return Security::permissionFailure($this);
    }
```

With my EditForm function being:
```
public function EditForm()
    {
        $agency = Agency::get()->filter('EAASAbbreviation', $this->request->param('ID'))->limit(1);

        return $this->customise($agency->first());
        $agency = $this->getAgency();
        $form = AgencyForm::create($this, 'EditForm');
        $form->addExtraClass('form');
        $form->loadDataFrom($agency);
        return $form;
    }
```

I then was calling $EditForm in my template.

I changed edit() and EditForm() to the following at it worked:
```
    public function edit()
    {
        if($this->canEditAgency())
        {
            $agency = $this->getAgency();

            $form = $this->EditForm();

            $form->addExtraClass('form');

            $form->loadDataFrom($agency);

            return $this->renderWith(['AgencyPage_EditForm', 'Page'], ['EditForm' => $form]);
        }
        return Security::permissionFailure($this);
    }

    public function EditForm()
    {
        $form = AgencyForm::create($this, 'EditForm');
        return $form;
    }
```

Not 100% sure, but I'm assuming something was initialising in the first EditForm that was in the second? It works now and seems to be a user error. If you have any idea why it now works I'd love to hear them but I will close this issue anyway.

Thanks again.
