### ISSUE TITLE
404 error on front-end on 'upload' action

### ISSUE THREAD

**Issue by nimeso** [unclecheese/silverstripe-dropzone#12]
1. I am creating a new DataObject (It does not exist yet) on the front-end using a form
2. The data object has_one ListingImage that I'm using dropzone for
3. I drag my image file in and I get the progress bar and prefly see the thumbnail
4. My network console says its trying POST to http://mysite/profile/CreateListingForm/field/ListingImage/upload but it returns a 404
5. I have tried adding 'upload' to my $allowed_actions with no luck :(

Could this be because the DataObject has not been created yet? What am I doing wrong?

**Comment by unclecheese** [comment]
Just curious.. what was it?

**Comment by nimeso** [comment]
Forgot to add my form to $allowed_actions ;)

On Tue, May 26, 2015 at 10:17 AM, unclecheese <notifications@github.com>
wrote:

> Just curious.. what was it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/unclecheese/silverstripe-dropzone/issues/12#issuecomment-105325875>
> .
>



-- 
  q-p
 /\"/\
(`=*=') JAMIE BARKER
 ^---^`-._

   P: +64 3 338 2482
   Skype: jam.dog

**Comment by silverstripe-elliot** [comment]
I also ran into this problem. To clarify what @nimeso did to resolve, I added the following to `allowed_actions`:
```php
'MyFormName/field/Photos/upload'
```

**Comment by unclecheese** [comment]
@silverstripe-elliot You should only have to add `MyFormName` to the `allowed_actions`, which should be the case for any form.
