### ISSUE TITLE
Problems using on a pagetype in the CMS

### ISSUE THREAD

**Issue by anselmdk** [unclecheese/silverstripe-dropzone#13]
I've had trouble using this on a pretty clean backend using the `3.1.x-dev` versions of both cms and framework.

See screenshots.

This happened when I first installed it:

![screenshot 2015-05-27 10 25 49](https://cloud.githubusercontent.com/assets/1316533/7831871/fb138044-045a-11e5-81ec-3a352bbeb523.png)

After a little debugging I tried renaming `FileAttachmentField_holder.ss` to `FileAttachmentField.ss`, which made it look a lot better:

![screenshot 2015-05-27 10 25 01](https://cloud.githubusercontent.com/assets/1316533/7831900/2449ff2e-045b-11e5-9dd7-debf9adf8fa3.png)

Still no joy though, as uploaded images are not being saved, and there's no "upload" button.

This is my getcms method:

```php
/**
 * @return FieldList
 */
public function getCMSFields() {
	$fields = parent::getCMSFields();
	$fields->removeByName('Content');
	$fields->addFieldsToTab(
		'Root.Main',
		[
			FileAttachmentField::create('Image1', 'Top Image')
				->setView('grid')
				->setFolderName(self::UPLOAD_FOLDER)
				->setAutoProcessQueue(true)
				->imagesOnly()
			,
			FileAttachmentField::create('Image2', 'About Image')
				->setView('grid')
				->setFolderName(self::UPLOAD_FOLDER)
				->imagesOnly()
		]
	);
	return $fields;
}
```

You see I also tried experimenting with `setAutoProcessQueue(true)`.

Am I missing anything?

**Comment by unclecheese** [comment]
Are you using the display_logic module?

**Comment by anselmdk** [comment]
Yes, that's installed.

**Comment by unclecheese** [comment]
That's the issue. What release of display logic? I think 1.2 is the one that is compatible.

**Comment by anselmdk** [comment]
Oh, it was hard coded to an older version, good catch! It works now. I'll close the issue.
