### ISSUE TITLE
Reseting/destroying uploaded images using javascript/jquery

### ISSUE THREAD

**Issue by nimeso** [unclecheese/silverstripe-dropzone#2]
I'm sending my form data via ajax and I need to reset/remove any uploaded images from the dropzone after the form has been submitted. So far I have:

```js
$(".input-attached-file").remove();
$(".file-attachment-field-previews li").remove();
$("#ImageDropzone").removeClass("dz-max-files-reached");
```
But the dz-max-files-reached class keeps coming back... I get the following error in the dropzone thumbnail 'OH NO! You can not upload any more files.'

**Comment by unclecheese** [comment]
Yeah, good one. The API for the upload interface needs to be exposed to browser globals. If you look at `file_attachment_field.js` you'll see there are public methods available that clear the queue, but you don't have access to that object in the user space. I'll write something up that injects the `UploadInterface` object into a browser global, like, say, `window.dropzones[your_field_id]`. Would that make sense?

**Comment by nimeso** [comment]
Sounds perfect! your a god! I'd try and hack it myself but my 'to do list' is crazy! Thanks heaps for the module... it's great! works perfect :)

**Comment by unclecheese** [comment]
Added to eb4a5e578c36a1a8ef652de1c9e69da84de8cc43. See new README section for documentation. Let me know how it works!

**Comment by nimeso** [comment]
perfect :)
