### ISSUE TITLE
FileAttachmentField Template Not Being Loaded

### ISSUE THREAD

**Issue by purplespider** [unclecheese/silverstripe-dropzone#3]
Here's an odd one. Added a FileAttachmentField to my form, but it only loads using the FileField template: 
![](http://spdr.me/1doGd+)

However, if I rename **FileAttachementField_holder.ss** to **FileAttachementField.ss** it loads fine.

Any idea what could be causing this?

**Comment by unclecheese** [comment]
Are you using bootstrap forms and/or display_logic?

**Comment by purplespider** [comment]
Ah yes. I have display_logic installed, and I'm actually using [Foundation Forms](https://github.com/rywa/silverstripe-foundation-forms) for that particular form.

If I remove both, it works! But removing just one doesn't.

Any way around this?

**Comment by unclecheese** [comment]
Use the latest version. dev-master, soon to be 1.2. 

The issue is the template overrides imposed by display-logic. In 1.2 they will be all removed for the most part. I just pushed up that change last week, so it hasn't been tested very much, but it should sort it for you.

**Comment by purplespider** [comment]
Nice one! That worked a treat!

And to make it work with Foundation Forms, I've just duplicated the template in my project as FoundationFileAttachmentField_holder.ss

Thanks!
