### ISSUE TITLE
Unknown function getdisplayfoldername

### ISSUE THREAD

**Issue by hailwood** [unclecheese/silverstripe-dropzone#32]
Not sure where it has come from, but when trying to select files from the cms we are getting a call to unknown function getdisplayfoldername.

This extension below fixes it for me but we might want to add the function to `FileAttachmentField`.

```php
class FileAttachmentFieldExtension extends Extension {

    private static $allowed_actions = [
        'getdisplayfoldername'
    ];

    public function getdisplayfoldername() {
        return $this->owner->getFolderName();
    }
}
````

**Comment by unclecheese** [comment]
Pretty sure this is fixed in 1.1.1.

https://github.com/unclecheese/silverstripe-dropzone/commit/c5f928de49b6e8907b0e439f435f61c41a698058

**Comment by hailwood** [comment]
@unclecheese That's the current version i'm using (it's pulled in via kickassets).

**Comment by unclecheese** [comment]
OK, looks like it wasn't. Since this is a new feature, I've tagged it as 1.2, and updated KickAssets accordingly (3.1.1) to use Dropzone 1.2

**Comment by hailwood** [comment]
@unclecheese Cheers!
