### ISSUE TITLE
I can't handle sub-URLs of a Form object.

### ISSUE THREAD

**Issue by purplespider** [unclecheese/silverstripe-dropzone#4]
Sorry, 2nd issue: Upon attempting to upload any file, it just says:

    OH NO!
    I can't handle sub-URLs of a Form object.

![](http://spdr.me/HONI+)

Just using ````FileAttachmentField::create('Image', 'Logo for brick')```` in a simple Form.

**Comment by unclecheese** [comment]
What’s the URL for the XHR?

aaron_carlino: {
web_developer: “leftandmain.com"
}

**Comment by purplespider** [comment]
/buy-your-brick/BrickForm/field/Image/upload

![](http://spdr.me/RC5R+)

**Comment by unclecheese** [comment]
First I’ve seen this one. If you access that URL in your browser, and append ?debug_request=1 does it tell you anything?

It should be resolving /BrickForm/ to your allowed_action for ‘BrickForm’, ‘field/Image’, as a handler against Form, and ‘upload’ as an action on FileAttachmentField.

At what point is it failing?  

aaron_carlino: {
web_developer: “leftandmain.com"
}

**Comment by purplespider** [comment]
Here's the result of that, it's bound to be something obvious: http://spdr.me/1aNK7

**Comment by purplespider** [comment]
Bah, think I've worked it out. I was conditionally showing the upload field, and on a file upload submission it obviously wasn't meeting the condition to show the field, so the field didn't exist to process the upload! 

I had tested it in a basic form but noticed a different error in it.

I'll tweak to fix it. Apologies. Thank god its Friday! :)
