### ISSUE TITLE
Saving into DataObjects not just files

### ISSUE THREAD

**Issue by KINKCreative** [unclecheese/silverstripe-dropzone#40]
@unclecheese is one able to use it to save has_many objects other than Files, so that e.g. an item can have a custom title, caption along with the file?

**Comment by unclecheese** [comment]
It's a nice idea, but it's really out of scope for this module. It's just an upload field, and I think it's best kept that way. I see your point that it's just one field, (e.g. Title), but that just opens the door to everything under the sun (has_one dropdowns, datepicker fields, nested uploads.. oh the humanity...)

I believe Dropzone now works with the GridFieldBulkUpload (???) component, which would be a more appropriate and scalable way for you to enjoy functionality like this.

**Comment by KINKCreative** [comment]
Yeah I was just asking to see if it existed if it's not documented. There's no Silverstripe publick Slack is there? :) Thanks!
