### ISSUE TITLE
Resample image on upload

### ISSUE THREAD

**Issue by mschilder** [unclecheese/silverstripe-dropzone#41]
Hi!

Sure looking awesome, this module! However we just got used to the auto-resample-if-above-certain-dimensions-feature from heyday/silverstripe-optimisedimage and that doesn't work anymore when using dropzone. 

So... would it be a nice feature to add to dropzone. That provides users with the best UX as they don't have to resize images themselves. What do you think?

**Comment by mschilder** [comment]
Wow, it appeared that I had to raise PHP's mem limit. Afterwards both modules did work together. Sorry, this non-issue may be closed :)

**Comment by unclecheese** [comment]
Sounds like a nice module. I'll have to check that one out. Thanks!
