### ISSUE TITLE
max upload size is misreported

### ISSUE THREAD

**Issue by mikeyc7m** [unclecheese/silverstripe-dropzone#42]
The upload size is reported from php post_max_size and upload_max_filesize and recalculated into bytes. But the recalculation is wrong, get_filesize_from_ini uses 1000 instead of 1024.

Suggested fix:
`return floor($bytes/(1024*1024))`

**Comment by unclecheese** [comment]
Cheers. https://github.com/unclecheese/silverstripe-dropzone/commit/0f5a9bcab98581a5faa7ada2e18e30492c0ff2e3
