### ISSUE TITLE
How to attach existing images to edit form frontend

### ISSUE THREAD

**Issue by darjus01** [unclecheese/silverstripe-dropzone#45]
all images saved in add form: `$EstateImages = EstateImage::get()->filter(array('EstateID' => $EstateID ));`

formfield: `$fields->push(FileAttachmentField::create('EstateImages', 'Nuotraukos')->sortable()->setSortableColumn('SortOrder')->setFolderName('/estates_images/' . date('Ymd') . "_" . Member::currentUserID())->setMultiple(true)->setView('grid')->setAutoProcessQueue(true));`
        
how to attach to this form field? please help

**Comment by unclecheese** [comment]
If you're using `$form->loadDataFrom($myDataObject);` it should pull them in. Otherwise, just use `->setValue($arrayOfIDs);`

**Comment by darjus01** [comment]
$arrayOfIDs is ids of images or ids of EstateImage object?

**Comment by darjus01** [comment]
Thx a lot for advice, array of image ids solved all, thx for asnwer and wonderful module :)
