### ISSUE TITLE
Limit number of files uploadable

### ISSUE THREAD

**Issue by sanderha** [unclecheese/silverstripe-dropzone#54]
Is there a way to limit the number of files a user can upload? Much like ``` UploadField ``` has a ``` setAllowedMaxFileNumber ```  method.

**Comment by unclecheese** [comment]
Yeah, there's a `maxFiles` setting. https://github.com/unclecheese/silverstripe-dropzone/blob/master/javascript/dropzone.js#L302

Problem is there's no API for it. Can you try creating:

```php
public function setMaxFiles($num)
{
    $this->settings['maxFiles'] = $num;
    return $this;
}
```

And if that works, submit as a PR?

**Comment by sanderha** [comment]
It works great, awesome module :)

**Comment by unclecheese** [comment]
Cheers!
