### ISSUE TITLE
Possible bug with filenames?

### ISSUE THREAD

**Issue by sanderha** [unclecheese/silverstripe-dropzone#60]
This issue might not be a problem with this module, but I figured I'd ask anyway. 

I am using dropzone in a frontend form. This form is used for job applications where people upload their CV, picture etc. This information/files is than saved onto a ``` JobApplication ``` dataobject, which has some normal fields, and a many many relation to File. There is also send an Email with these files attached.

It seems to be working fine most of the time, until the client reported an issue where some applications had a relation to a file, which did not belong to them. This problem arose where the filenames were very generic i.e. "CV" or so, so that they were renamed to something like "CV1". 

**The question:** Could there be an issue files being overwritten if they are uploaded at the same time or something?

I save the data like this:
```php
		$object = JobApplication::create();
		foreach ($data['Attachments'] as $file) {
			$file_object = File::get()->byID($file); // $file is just ID
			$folder = Folder::find_or_make('jobs/applications');
			$object->Attachments()->add($file);
			if ($folder) {
				$file_object->setParentID($folder->ID);
			}
			$file_object->write();
		}
		$form->saveInto($object);
```

I do the foreach because I need to move the files attached to the object, to another folder. WHen files are first uploaded, they end up in a "temp" folder.

**Comment by sanderha** [comment]
As I thought, something was wrong with my code. Nothing to do with this awesome module :) 

It seemed moving of the file when there were existing files in the new folder with the same name messed things up.

**Comment by unclecheese** [comment]
Glad you got it sorted, and thanks for the kind words. :)
