### ISSUE TITLE
validate and getValidFileIDs

### ISSUE THREAD

**Issue by lekoala** [unclecheese/silverstripe-dropzone#68]
The validate method checks for validIDs which is a good thing, but relies on something set in the session. So, if you have a form with let's say Pictures, they are not going to be valid next time you visit the same form (at least, on my setup).

This is why I had to do something like that

   $uploader->addValidFileIDs($this->dataobject->Pictures()->column('ID'));

To make it work, instead on relying on loadDataFrom to setValue and make sure the loaded files are valid.

Is this the expected use? having to call addValidFileIDs manually seems more work that it needs to.

**Comment by SilbinaryWolf** [comment]
Fixed in https://github.com/unclecheese/silverstripe-dropzone/pull/78

**Comment by SilbinaryWolf** [comment]
@lekoala If this looks fixed on your end. Mind closing this?

**Comment by lekoala** [comment]
yes, perfect
