### ISSUE TITLE
Does not work with Translatable module

### ISSUE THREAD

**Issue by tubbs** [unclecheese/silverstripe-dropzone#7]
I modified file_attachment_field_backend.js to preserve URL parameters.
line 9:
var iParams = config['urlSelectDialog'].indexOf('?'),
      iframeUrl = config['urlSelectDialog'].substr(0, iParams),
      iframeParams = config['urlSelectDialog'].substr(iParams+1);

line 18:
dialog.ssdialog({iframeUrl: iframeUrl + '?' + iframeParams, height: 550});

and line 35:
$.ajax({
  url: iframeUrl+'/filesbyid?ids='+ids.join(',') + '&' + iframeParams,

**Comment by unclecheese** [comment]
Awesome. Could you please submit a PR?

**Comment by tubbs** [comment]
Wow, you're fast. I will submit a PR ASAP. Maybe not as fast as you. ;)

**Comment by unclecheese** [comment]
This module is my baby right now, so I look after it pretty closely. ;-)

You can even just hit the "edit" button on the file_attachment_field_backend.js file and paste in yours.

**Comment by tubbs** [comment]
Done. Very nice baby, I like it!

**Comment by unclecheese** [comment]
Awesome. Glad to hear it. Lots more stuff on the way. Integrating this with AssetAdmin, and it's going to be awesome.
