### ISSUE TITLE
IE9 Bug: classList does not exist

### ISSUE THREAD

**Issue by SilbinaryWolf** [unclecheese/silverstripe-dropzone#74]
Need to either polyfill or use archaic methods of class detection here. (And possibly in other places)

file_attachment_field.js
```
if(this.node.classList.contains('uploadable')) {
this.backend = new backend(this.node, this.settings);
}
```

**Comment by unclecheese** [comment]
Pretty sure that's deliberate, as IE9 isn't a targeted browser. The file API isn't supported in IE9.

**Comment by SilbinaryWolf** [comment]
As per my PR, it should gracefully fallback to "Your browser is not supported".
