### ISSUE TITLE
Feature: Limit image resolution

### ISSUE THREAD

**Issue by jonom** [unclecheese/silverstripe-dropzone#9]
How did I miss this module getting released? Looks amazing!

I just have a feature request, don't know if this is even possible but it would be great if there was a `setMaxResolution($totalPixels)` validation option to prevent users uploading high resolution images.

[GD can easily crash](https://github.com/silverstripe/silverstripe-framework/pull/2859) when trying to resize high resolution images, and the problem has nothing to do with filesize and everything to do with the number of pixels in the image. So a 5kb PNG could cause a crash just as easily as a 5mb JPEG.

@kinglozzer developed a fix to prevent this crash happening more than once for a particular image, but client-side validation could go a long way towards preventing a crash ever happening in the first place.

Thanks for another great looking module, looking forward to trying it out.

**Comment by unclecheese** [comment]
Ha! Yeah, thanks man, I need to do more self-promotion. :-) I'll chuck it up on my Twitter and Facebook now.

Max resolution would be awesome. I have not yet looked, but are there JavaScript APIs for that? If so, we can easily do it.

**Comment by jonom** [comment]
Just did a quick search and looks like it's possible. Here's an example of reading the resolution http://jsbin.com/oTAtIpA/3/edit?html,css,js,output and here's a plugin for uploading an image that's been resized client-side... that would be a pretty killer feature! https://github.com/rossturner/HTML5-ImageUploader

**Comment by unclecheese** [comment]
Ah, of course. Image.width and Image.height. That API has been around forever!

So you're imagining something like this:

$uploader->seMaxResolution(5000000);

1280x1280 = OK
3000x2000 != OK

**Comment by jonom** [comment]
Yeah exactly like that. Then if it fails, it would be cool if the error message considered the aspect ratio of the image and told you what resolution to resize the image to. Using your example:
```php
$imageW = 3000;
$imageH = 2000;
$maxPixels = 5000000;
// Calculate ratio of height to width
$ratio = $imageH / $imageW; // (.6666667)
// Calculate maximum width and round down
$maxWidth = floor( sqrt( $maxPixels / $ratio ) ); // (2738)
// Calculate maximum height and round to whole pixel 
$maxHeight = round( $maxWidth * $ratio ); // (1825)
// Maybe need to floor the height as well to ensure we're never oversize by a pixel or two, not sure
```
**The resolution of this image is too high. Please resize this image down to 2738px wide by 1825px tall or less before uploading.**

**Comment by jonom** [comment]
Or even cooler if it automatically resized the image directly in the browser before uploading. But that sounds a lot harder.

**Comment by unclecheese** [comment]
I've added this feature to the master branch. Could you please review f8ff31c5ae2ba4ece8bd30137917f4d46153e464 to see if it meets your expectations for this?

**Comment by jonom** [comment]
:joy: It's beautiful

Thanks so much! I've only tried it in the CMS so far but worked like a charm. This is going to be really handy for me.

One thing I couldn't quite tell from the commit, will it be possible to set a global max resolution for this field through the config system? That would be a nice feature, so I can set a reasonable default and make sure my clients never upload 10 megapixel photos.

**Comment by unclecheese** [comment]
Actually, it looks like you can.. 

```yaml
FileAttachmentField:
  defaults:
    max_resolution: 9999
```

**Comment by jonom** [comment]
Nice!
